apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.authConfig.name }}
  namespace: {{ .Release.Namespace }}
data:
  INSECURE_SKIP_VERIFY: "{{ .Values.authConfig.insecureSkipVerify }}"
  KUBE_CLIENT_ID: "{{ .Values.authConfig.kubeClientID }}"
  KUBE_AUTH_URL: "https://oauth-openshift.apps.{{ .Values.clusterName }}.{{ .Values.clusterDomain }}/oauth/authorize"
  KUBE_TOKEN_URL: "https://oauth-openshift.apps.{{ .Values.clusterName }}.{{ .Values.clusterDomain }}/oauth/token"
  KUBE_USERINFO_URL: "https://api.{{ .Values.clusterName }}.{{ .Values.clusterDomain }}:{{ .Values.apiPort }}/apis/user.openshift.io/v1/users/~"
  KUBE_API_SERVER: "https://api.{{ .Values.clusterName }}.{{ .Values.clusterDomain }}:{{ .Values.apiPort }}"
  ALLOWED_ORIGIN_REGEX: "{{ .Values.allowedOriginRegex }}"
  DEFAULT_PAGINATION_LIMIT: "{{ .Values.defaultPaginationLimit }}"