#!/bin/bash

CLUSTER_NAME=$1
CLUSTER_DOMAIN=$2
KUBE_AUTH_BASE_URL="https://oauth-openshift.apps.${CLUSTER_NAME}.${CLUSTER_DOMAIN}"
KUBE_API_BASE_URL="https://api.${CLUSTER_NAME}.${CLUSTER_DOMAIN}:6443"

INSECURE_SKIP_VERIFY=true
KUBE_CLIENT_ID="openshift-challenging-client"
KUBE_AUTH_URL="${KUBE_AUTH_BASE_URL}/oauth/authorize"
KUBE_TOKEN_URL="${KUBE_AUTH_BASE_URL}/oauth/token"
KUBE_USERINFO_URL="${KUBE_API_BASE_URL}/apis/user.openshift.io/v1/users/~"
KUBE_API_SERVER="${KUBE_API_BASE_URL}"

cat <<EOF > "${3}"
INSECURE_SKIP_VERIFY=${INSECURE_SKIP_VERIFY}
KUBE_CLIENT_ID=${KUBE_CLIENT_ID}
KUBE_AUTH_URL=${KUBE_AUTH_URL}
KUBE_TOKEN_URL=${KUBE_TOKEN_URL}
KUBE_USERINFO_URL=${KUBE_USERINFO_URL}
KUBE_API_SERVER=${KUBE_API_SERVER}
EOF