kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-proxy-cluster-role
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - rcs.dana.io
    resources:
      - capps
      - capprevisions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - record.dns.crossplane.io
    resources:
      - cnamerecords
      - cnamerecords/status
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-proxy-role-binding-cluster
subjects:
  - kind: ServiceAccount
    name: cluster-proxy
    namespace: open-cluster-management-agent-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proxy-cluster-role
